/**
 * Preview panel UI for real-time mode
 * Creates .prompt.md files for easy editing and reuse
 */

import * as vscode from "vscode";

export class PreviewPanel {
  /**
   * Show inline preview by creating a .prompt.md file
   * Returns the action and prompt to use, or undefined if cancelled
   */
  async showInlinePreview(
    original: string,
    optimized: string,
  ): Promise<{ action: string; prompt: string } | undefined> {
    try {
      // Create and open the .prompt.md file for review
      await this.showComparisonDocument(original, optimized);

      // Return optimized prompt to continue processing
      // User can edit the file and use it later with VS Code's native prompt features
      return { action: "submit", prompt: optimized };
    } catch (error) {
      vscode.window.showErrorMessage(
        `Preview error: ${error instanceof Error ? error.message : String(error)}`,
      );
      return undefined;
    }
  }

  /**
   * Show comparison in a new document (for future enhancement)
   */
  async showComparisonDocument(
    original: string,
    optimized: string,
  ): Promise<void> {
    // Create a proper .prompt.md file that can be processed by VS Code
    const timestamp = new Date()
      .toISOString()
      .replace(/[:.]/g, "-")
      .slice(0, -5);
    const fileName = `optimized-prompt-${timestamp}.prompt.md`;

    const content = `${optimized}

<!--
Original Prompt:
${original}

Generated: ${new Date().toISOString()}
Mode: Real-time
Generated by Prompt Booster
-->`;

    // Try to save in workspace, fallback to untitled
    const workspaceFolders = vscode.workspace.workspaceFolders;

    if (workspaceFolders && workspaceFolders.length > 0) {
      // Save in workspace root
      const workspaceUri = workspaceFolders[0].uri;
      const fileUri = vscode.Uri.joinPath(workspaceUri, fileName);

      try {
        await vscode.workspace.fs.writeFile(
          fileUri,
          Buffer.from(content, "utf8"),
        );

        const doc = await vscode.workspace.openTextDocument(fileUri);
        await vscode.window.showTextDocument(doc, {
          preview: false,
          viewColumn: vscode.ViewColumn.Beside,
        });

        return;
      } catch (error) {
        // Fallback to untitled if write fails
        console.error("Failed to save prompt file:", error);
      }
    }

    // Fallback: open as untitled document
    const doc = await vscode.workspace.openTextDocument({
      content,
      language: "markdown",
    });

    await vscode.window.showTextDocument(doc, {
      preview: false,
      viewColumn: vscode.ViewColumn.Beside,
    });
  }
}
